export { default as Gallery } from './Gallery'
export { default as Home } from './Home'
export { default as Upload } from './Upload'
export { default as Mint } from './Mint'
export { default as Contact } from './Contact'
export { default as ImageDetail } from './ImageDetail'